# Generated by Django 3.1.4 on 2021-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField(verbose_name='订单总价')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('state', models.IntegerField(choices=[('0', '待支付'), ('1', '待发货'), ('2', '配送中'), ('3', '已签收'), ('4', '退货中'), ('5', '已关闭')], max_length=12, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='order_ware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ware_id', models.IntegerField(verbose_name='商品id')),
                ('order_id', models.IntegerField(verbose_name='订单id')),
                ('cur_price', models.FloatField(verbose_name='成交价格')),
                ('num', models.IntegerField(verbose_name='购买数量')),
            ],
            options={
                'verbose_name': '订单商品明细表',
                'verbose_name_plural': '订单商品明细表',
            },
        ),
        migrations.CreateModel(
            name='shopcart_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nums', models.IntegerField(verbose_name='购买数量')),
                ('ware_id', models.IntegerField(verbose_name='商品id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'verbose_name': '购物车信息',
                'verbose_name_plural': '购物车信息',
            },
        ),
    ]
