# Generated by Django 3.1.4 on 2021-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ware_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='商品名称')),
                ('size', models.CharField(max_length=100, verbose_name='商品规格')),
                ('level', models.CharField(max_length=100, verbose_name='商品类型级别')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('discount', models.FloatField(verbose_name='折后价格')),
                ('stock', models.IntegerField(verbose_name='库存数量')),
                ('sold', models.IntegerField(verbose_name='销售数量')),
                ('likes', models.IntegerField(verbose_name='被收藏数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('img_main', models.FileField(upload_to='img_main', verbose_name='主图路径')),
                ('img_detail', models.FileField(upload_to='img_detail', verbose_name='详情图路径')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Ware_level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=100, verbose_name='类型级别1')),
                ('second', models.CharField(max_length=100, verbose_name='类型级别2')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
    ]
